
  /*-------------------------------------------------------------------------------------------.
  |                                   [STAGING] PERSONS_DEMO                                   |
  |--------------------------------------------------------------------------------------------|
  | PROJECT       : DATA FRAMEWORK (Oracle) By Autonomous Database                             |
  | LAYER         : SOURCE                                                                     |
  | MODULE        : DEMO DATA                                                                  |
  | DESCRIPTION   : Datos de de prueba generado por intervalos.                                |
  |------------------.-------------------------------------------------------------------------|
  | STEP             | DETAIL                                                                  |
  |------------------|-------------------------------------------------------------------------|
  | DROP_TABLE       | Eliminar tabla si existe.                                               |
  | CREATE_TABLE     | Crear tabla.                                                            |  
  | INSERT_TABLE     | Insertar datos de prueba.                                               |
  `-------------------------------------------------------------------------------------------*/
  
  --[DROP_TABLE]
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STG1.PERSONS_DEMO';
    EXECUTE IMMEDIATE 'DROP TABLE STG2.PERSONS_DEMO';
    EXECUTE IMMEDIATE 'DROP TABLE STG3.PERSONS_DEMO';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
        RAISE;
      END IF;
  END;
  /

  --[CREATE_TABLE]
  CREATE TABLE STG1.PERSONS_DEMO (
    person_id               NUMBER GENERATED BY   DEFAULT AS IDENTITY,
    first_name              VARCHAR2(50)          NOT NULL,
    last_name               VARCHAR2(50)          NOT NULL,    
    creation_date           TIMESTAMP             DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY(person_id)
  );
  CREATE TABLE STG2.PERSONS_DEMO (
    person_id               NUMBER GENERATED BY   DEFAULT AS IDENTITY,
    first_name              VARCHAR2(50)          NOT NULL,
    last_name               VARCHAR2(50)          NOT NULL,    
    creation_date           TIMESTAMP             DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY(person_id)
  );
  CREATE TABLE STG3.PERSONS_DEMO (
    person_id               NUMBER GENERATED BY   DEFAULT AS IDENTITY,
    first_name              VARCHAR2(50)          NOT NULL,
    last_name               VARCHAR2(50)          NOT NULL,    
    creation_date           TIMESTAMP             DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY(person_id)
  );

  --[INSERT_TABLE]
  BEGIN
    FOR l_counter IN 1..20
    LOOP
      INSERT INTO STG1.PERSONS_DEMO (first_name,
                                     last_name)
                             VALUES (dbms_random.string('X', 20),
                                     dbms_random.string('X', 20));
      DBMS_OUTPUT.PUT_LINE('STG1: '||TO_CHAR(l_counter));
    END LOOP;
  END;
  /

  BEGIN
    FOR l_counter IN 1..20
    LOOP
      INSERT INTO STG2.PERSONS_DEMO (first_name,
                                     last_name)
                             VALUES (dbms_random.string('X', 20),
                                     dbms_random.string('X', 20));
      DBMS_OUTPUT.PUT_LINE('STG1: '||TO_CHAR(l_counter));
    END LOOP;
  END;
  /

  BEGIN
    FOR l_counter IN 1..20
    LOOP
      INSERT INTO STG3.PERSONS_DEMO (first_name,
                                     last_name)
                             VALUES (dbms_random.string('X', 20),
                                     dbms_random.string('X', 20));
      DBMS_OUTPUT.PUT_LINE('STG1: '||TO_CHAR(l_counter));
    END LOOP;
  END;
  /